version: '3'

services:
  app-prueba:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - "db-prueba"

  web-prueba:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8080:80"

  db-prueba:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./sqlite-data:/mydatabase
    restart: always

volumes:
  sqlite-data:
